spring:
  config:
    activate:
      on-profile: stg
  activemq:
    in-memory: false
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USER:}
    password: ${ACTIVEMQ_PASSWORD:}
  data:
    mongodb:
      uri: ${GYMCRM_STG_MONGODB_URI}
