server:
  port: 8081

spring:
  application:
    name: gym-crm
  datasource:
    url: jdbc:h2:mem:gymcrm

logging:
  file:
    name: logs/gym-crm.log
  pattern:
    level: "%5p [txId: %X{transactionId}]"