spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./data/gymcrm-dev;AUTO_SERVER=TRUE;MODE=PostgreSQL
    username: gymcrm_dev
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.gymcrm: DEBUG
