server:
  port: 8081

spring:
  application:
    name: gym-crm
  profiles:
    active: local

logging:
  file:
    name: logs/gym-crm.log
  pattern:
    level: "%5p [txId: %X{transactionId}]"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus
